import type {
  AppNotification,
  Developer,
  DeveloperAccount,
  Project,
  Thread,
} from "./types";

export const DEVELOPERS: Developer[] = [
  {
    id: "d1",
    name: "Maya Chen",
    headline: "End-to-end product engineer, payments and auth",
    country: "Singapore",
    rate: 68,
    rating: 4.9,
    delivered: 38,
    skills: ["React", "Node", "Postgres", "Stripe"],
    idVerified: true,
    interviewScore: 92,
    tier: "Principal",
  },
  {
    id: "d2",
    name: "Arjun Mehta",
    headline: "Ships locked scopes in two to four weeks",
    country: "India",
    rate: 44,
    rating: 4.8,
    delivered: 27,
    skills: ["Next.js", "Supabase", "Tailwind", "Razorpay"],
    idVerified: true,
    interviewScore: 86,
    tier: "Verified",
  },
  {
    id: "d3",
    name: "Sofia Alvarez",
    headline: "AI features that survive production",
    country: "Spain",
    rate: 72,
    rating: 5,
    delivered: 19,
    skills: ["Python", "RAG", "FastAPI", "AWS"],
    idVerified: true,
    interviewScore: 94,
    tier: "Principal",
  },
  {
    id: "d4",
    name: "Noah Okonkwo",
    headline: "Pixel-faithful builds from approved screens",
    country: "Nigeria",
    rate: 51,
    rating: 4.7,
    delivered: 41,
    skills: ["React", "Design systems", "Firebase"],
    idVerified: true,
    interviewScore: 81,
    tier: "Verified",
  },
  {
    id: "d5",
    name: "Lena Fischer",
    headline: "Data-heavy internal tools and dashboards",
    country: "Germany",
    rate: 79,
    rating: 4.9,
    delivered: 23,
    skills: ["TypeScript", "Postgres", "Kubernetes"],
    idVerified: true,
    interviewScore: 89,
    tier: "Principal",
  },
];

/** A developer who has verified identity but has not paid to bid yet. */
export const NEW_DEVELOPER_ACCOUNT: DeveloperAccount = {
  identityStatus: "approved",
  interviewStatus: "approved",
  membershipPaid: false,
  tier: "Verified",
  interviewScores: [
    { label: "Security practices", score: 88 },
    { label: "Efficiency under time pressure", score: 84 },
    { label: "Maintainability and structure", score: 91 },
    { label: "Recovery from mistakes", score: 79 },
  ],
};

export const PROJECTS: Project[] = [
  {
    id: "p1",
    title: "Customer portal with subscription billing",
    org: "Northline Labs",
    scale: "Startup",
    category: "Web application",
    outcome:
      "Our customers should log in, see their invoices, update payment methods, and download usage reports without emailing support.",
    budgetMin: 9000,
    budgetMax: 14000,
    monthlyOps: 240,
    timelineWeeks: 7,
    skills: ["React", "Node", "Stripe", "Postgres"],
    stage: "locked",
    lockedAt: "12 Jul 2026",
    lockId: "LOCK-4F2A91",
    postedAgo: "2 hours ago",
    warrantyDays: 30,
    scope: [
      {
        id: "s1",
        label: "Customer sign-in and account",
        detail: "Email and SSO login, password reset, profile settings.",
        included: true,
        acceptanceCriteria:
          "A customer can register, sign in, reset a password and update their profile.",
      },
      {
        id: "s2",
        label: "Invoice history and downloads",
        detail: "List of invoices with PDF download and payment status.",
        included: true,
        acceptanceCriteria:
          "Every past invoice is listed and downloads as a PDF within two seconds.",
      },
      {
        id: "s3",
        label: "Payment method management",
        detail: "Add, remove, and set default card through Stripe.",
        included: true,
        acceptanceCriteria:
          "A card can be added, removed and set as default without support help.",
      },
      {
        id: "s4",
        label: "Usage reports export",
        detail: "CSV export filtered by date range.",
        included: true,
        acceptanceCriteria: "A date-filtered CSV downloads with correct totals.",
      },
      {
        id: "s5",
        label: "Native mobile app",
        detail: "Explicitly excluded from this contract.",
        included: false,
      },
    ],
    versions: [
      { version: 1, reason: "Requirement locked", createdAt: "12 Jul 2026" },
    ],
    publicBidCount: 2,
    milestones: [
      {
        id: "m1",
        title: "Authentication and account shell",
        description: "Sign-in, password reset, profile settings.",
        amount: 4000,
        status: "released",
        dueOn: "19 Jul 2026",
        deliverable: {
          summary: "Auth flows complete with SSO and reset covered by tests.",
          previewUrl: "https://staging.example.com",
          repositoryUrl: "https://github.com/example/portal",
          submittedAt: "18 Jul 2026",
          buyerFeedback: "Matches scope item 1. Accepted.",
        },
      },
      {
        id: "m2",
        title: "Invoices and payment methods",
        description: "Invoice list, PDF download, card management.",
        amount: 5000,
        status: "submitted",
        dueOn: "02 Aug 2026",
        deliverable: {
          summary:
            "Invoice list and PDF export live. Card management wired to Stripe test mode.",
          previewUrl: "https://staging.example.com/billing",
          submittedAt: "01 Aug 2026",
        },
      },
      {
        id: "m3",
        title: "Usage reports and handover",
        description: "CSV export, documentation, deployment runbook.",
        amount: 3500,
        status: "pending",
        dueOn: "16 Aug 2026",
      },
    ],
    changeOrders: [
      {
        id: "co1",
        title: "Add annual invoice summary PDF",
        description:
          "A single yearly statement combining all invoices, requested after the lock.",
        status: "priced",
        amount: 900,
        addedWeeks: 1,
        raisedBy: "buyer",
        createdAt: "24 Jul 2026",
      },
    ],
    bids: [
      {
        id: "b1",
        developerId: "d1",
        developerName: "Maya Chen",
        country: "Singapore",
        tier: "Principal",
        amount: 12500,
        monthlyOps: 220,
        weeks: 6,
        note: "I have shipped this exact billing surface four times. Fixed price against your locked scope.",
        status: "awarded",
        submittedAt: "12 Jul 2026",
      },
      {
        id: "b2",
        developerId: "d2",
        developerName: "Arjun Mehta",
        country: "India",
        tier: "Verified",
        amount: 9400,
        monthlyOps: 180,
        weeks: 7,
        note: "Can start Monday. Weekly demo against each locked scope item.",
        status: "declined",
        submittedAt: "12 Jul 2026",
      },
    ],
    reviews: [],
    awardedTo: "Maya Chen",
  },
  {
    id: "p2",
    title: "Online ordering for a two-location bakery",
    org: "Rose Street Bakery",
    scale: "Local business",
    category: "Online store",
    outcome:
      "Customers order cakes online, pick a pickup slot, and pay. I get one screen showing today's orders.",
    budgetMin: 2200,
    budgetMax: 3800,
    monthlyOps: 60,
    timelineWeeks: 4,
    skills: ["Next.js", "Payments", "Mobile-first"],
    stage: "locked",
    lockedAt: "14 Jul 2026",
    lockId: "LOCK-77C0B4",
    postedAgo: "6 hours ago",
    warrantyDays: 30,
    scope: [
      {
        id: "s1",
        label: "Product catalogue with photos",
        detail: "Cakes and pastries with price and description.",
        included: true,
        acceptanceCriteria: "Owner can add a product with photo in under a minute.",
      },
      {
        id: "s2",
        label: "Pickup slot selection",
        detail: "Customer chooses a date and time window per location.",
        included: true,
        acceptanceCriteria: "Slots respect opening hours and daily capacity.",
      },
      {
        id: "s3",
        label: "Card payment at checkout",
        detail: "Single payment provider, no split payments.",
        included: true,
        acceptanceCriteria: "A test card completes an order end to end.",
      },
      {
        id: "s4",
        label: "Owner order screen",
        detail: "Today's orders with status toggle, works on a phone.",
        included: true,
        acceptanceCriteria: "Usable on a 5-inch phone without pinch zoom.",
      },
      {
        id: "s5",
        label: "Delivery and courier tracking",
        detail: "Not in this contract. Pickup only.",
        included: false,
      },
    ],
    versions: [
      { version: 1, reason: "Requirement locked", createdAt: "14 Jul 2026" },
    ],
    publicBidCount: 2,
    milestones: [],
    changeOrders: [],
    bids: [
      {
        id: "b4",
        developerId: "d4",
        developerName: "Noah Okonkwo",
        country: "Nigeria",
        tier: "Verified",
        amount: 2900,
        monthlyOps: 55,
        weeks: 3,
        note: "Mobile-first build. You will be able to run the whole shop from your phone.",
        status: "submitted",
        submittedAt: "14 Jul 2026",
      },
      {
        id: "b5",
        developerId: "d2",
        developerName: "Arjun Mehta",
        country: "India",
        tier: "Verified",
        amount: 2400,
        monthlyOps: 45,
        weeks: 4,
        note: "Fixed price. Includes a handover walkthrough on a video call.",
        status: "shortlisted",
        submittedAt: "14 Jul 2026",
      },
    ],
    reviews: [],
  },
  {
    id: "p3",
    title: "Internal claims triage tool",
    org: "Meridian Insurance",
    scale: "Enterprise",
    category: "Internal tool",
    outcome:
      "Claims staff should see incoming claims ranked by risk, open one, and record a decision with an audit trail.",
    budgetMin: 40000,
    budgetMax: 65000,
    monthlyOps: 1400,
    timelineWeeks: 14,
    skills: ["TypeScript", "Python", "SSO", "Audit logging"],
    stage: "locked",
    lockedAt: "09 Jul 2026",
    lockId: "LOCK-1B93EE",
    postedAgo: "1 day ago",
    warrantyDays: 45,
    scope: [
      {
        id: "s1",
        label: "SSO with corporate identity provider",
        detail: "SAML integration, role mapping for three roles.",
        included: true,
        acceptanceCriteria: "Staff sign in with corporate credentials only.",
      },
      {
        id: "s2",
        label: "Claim queue with risk ranking",
        detail: "Sortable queue, filters, assignment to reviewer.",
        included: true,
        acceptanceCriteria: "Queue loads 10,000 claims in under two seconds.",
      },
      {
        id: "s3",
        label: "Decision recording with audit trail",
        detail: "Immutable log of who decided what and when.",
        included: true,
        acceptanceCriteria: "Audit entries cannot be edited or deleted.",
      },
      {
        id: "s4",
        label: "Data residency in EU region",
        detail: "All storage and processing inside the EU.",
        included: true,
        acceptanceCriteria: "Infrastructure review confirms EU-only regions.",
      },
      {
        id: "s5",
        label: "Replacing the core policy system",
        detail: "Out of scope. Read-only integration only.",
        included: false,
      },
    ],
    versions: [
      { version: 1, reason: "Requirement locked", createdAt: "09 Jul 2026" },
    ],
    publicBidCount: 2,
    milestones: [],
    changeOrders: [],
    bids: [
      {
        id: "b6",
        developerId: "d5",
        developerName: "Lena Fischer",
        country: "Germany",
        tier: "Principal",
        amount: 58000,
        monthlyOps: 1300,
        weeks: 13,
        note: "EU residency and audit logging are my core work. References available.",
        status: "shortlisted",
        submittedAt: "09 Jul 2026",
      },
      {
        id: "b7",
        developerId: "d3",
        developerName: "Sofia Alvarez",
        country: "Spain",
        tier: "Principal",
        amount: 61000,
        monthlyOps: 1450,
        weeks: 14,
        note: "Risk ranking model plus the review workflow, evaluated weekly.",
        status: "submitted",
        submittedAt: "10 Jul 2026",
      },
    ],
    reviews: [],
  },
  {
    id: "p4",
    title: "Document question answering for a legal team",
    org: "Beacon Counsel",
    scale: "SMB",
    category: "AI feature",
    outcome:
      "Lawyers upload case PDFs and ask questions, and every answer cites the exact page it came from.",
    budgetMin: 15000,
    budgetMax: 24000,
    monthlyOps: 620,
    timelineWeeks: 9,
    skills: ["Python", "RAG", "React", "Security"],
    stage: "drafting",
    postedAgo: "3 hours ago",
    warrantyDays: 30,
    scope: [
      {
        id: "s1",
        label: "PDF upload and indexing",
        detail: "Bulk upload, per-matter folders.",
        included: true,
      },
      {
        id: "s2",
        label: "Question answering with citations",
        detail: "Every answer links to its source page.",
        included: true,
      },
      {
        id: "s3",
        label: "Access control per matter",
        detail: "Only assigned lawyers can open a matter.",
        included: true,
      },
      {
        id: "s4",
        label: "Automatic contract drafting",
        detail: "Under discussion, not yet locked.",
        included: false,
      },
    ],
    versions: [],
    publicBidCount: 2,
    milestones: [],
    changeOrders: [],
    bids: [],
    reviews: [],
  },
];

export const THREADS: Thread[] = [
  {
    id: "t1",
    projectId: "p1",
    subject: "Customer portal with subscription billing",
    counterpart: "Maya Chen",
    messages: [
      {
        id: "msg1",
        from: "buyer",
        authorName: "Northline Labs",
        body: "Milestone two looks close. Can you confirm the PDF export matches the invoice numbering we use in Xero?",
        sentAt: "01 Aug 2026, 10:12",
      },
      {
        id: "msg2",
        from: "developer",
        authorName: "Maya Chen",
        body: "Confirmed. Numbering pulls straight from the invoice record, so it will match Xero exactly.",
        sentAt: "01 Aug 2026, 10:31",
      },
    ],
  },
  {
    id: "t2",
    projectId: "p2",
    subject: "Online ordering for a two-location bakery",
    counterpart: "Arjun Mehta",
    messages: [
      {
        id: "msg3",
        from: "developer",
        authorName: "Arjun Mehta",
        body: "Quick question before you pick a bid: do both shops share one menu, or does each location price separately?",
        sentAt: "14 Jul 2026, 16:40",
      },
    ],
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    kind: "milestone",
    title: "Milestone submitted",
    body: "Maya Chen submitted “Invoices and payment methods” for review.",
    link: "/app/contract/p1",
    read: false,
    createdAt: "01 Aug 2026",
  },
  {
    id: "n2",
    kind: "change_order",
    title: "Change order priced",
    body: "Annual invoice summary PDF quoted at $900 and one extra week.",
    link: "/app/contract/p1",
    read: false,
    createdAt: "24 Jul 2026",
  },
  {
    id: "n3",
    kind: "bid",
    title: "New bid received",
    body: "Noah Okonkwo bid $2,900 on your bakery ordering requirement.",
    link: "/app/project/p2",
    read: true,
    createdAt: "14 Jul 2026",
  },
];

export const CATEGORY_OPTIONS = [
  { id: "store", label: "Sell online", hint: "Products, payments, orders" },
  { id: "booking", label: "Take bookings", hint: "Appointments, slots, reminders" },
  { id: "internal", label: "Replace spreadsheets", hint: "Internal tool for my team" },
  { id: "portal", label: "Customer portal", hint: "Logins, accounts, self-service" },
  { id: "ai", label: "Add an AI feature", hint: "Assistants, search, automation" },
  { id: "other", label: "Something else", hint: "Describe it in your own words" },
];

export const SCALE_OPTIONS = [
  { id: "Local business", label: "Local business", hint: "Shop, clinic, studio" },
  { id: "SMB", label: "Small company", hint: "10–200 people" },
  { id: "Startup", label: "Startup", hint: "Building a product" },
  { id: "Enterprise", label: "Enterprise", hint: "Procurement and compliance" },
];

export const MUST_HAVES = [
  "Works on phones",
  "Take payments",
  "Customer logins",
  "Admin dashboard",
  "Email or WhatsApp alerts",
  "Reports and exports",
  "Multiple locations",
  "Single sign-on",
  "Data stays in my region",
];
